# Generated by Django 4.2.5 on 2024-01-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_author_alter_receita_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Titulo'),
        ),
    ]
